 &files wffile='restart'/
 &force name='SV-bas', pairing='NONE' /
 &main mprint=10,mplot=100000,
  mrest=500000,writeselect='rc',
  imode=2,tfft=T,nof=1 /
 &grid nx=24,ny=24,nz=24,dx=1,dy=1,dz=1,
	periodic=F /
 &dynamic nt=25000, dt=0.2, mxpact=4, texternal=T/
 &extern ipulse=0,isoext=0,amplq0=5D-3,radext=200D0,widext=1D0,
         textfield_periodic=T /
 &fragments filename=1*'O16',fix_boost=T,
      fcent(1,1)=0,0,0    /
